name: Sparse Checkout Example

on:
  push:
    branches:
      - main

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sparse checkout, excluding scripts folder
        run: |
        git config core.sparseCheckout true
        echo '/*' > .git/info/sparse-checkout
        echo '!scripts' >> .git/info/sparse-checkout
        ls -la
      