name: Sparse Checkout Example

on:
  push:
    branches:
      - main

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !/scripts

      - name: Set up sparse-checkout
        run: |
          ls -la
