name: Sparse Checkout Example

on:
  push:
    branches:
      - main

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up sparse-checkout
        run: |
          echo '/*' > .git/info/sparse-checkout
          echo '!node_modules' >> .git/info/sparse-checkout
          git read-tree -mu HEAD
          ls -la