name: Sparse Checkout Example

on:
  push:
    branches:
      - main

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sparse checkout, excluding scripts folder
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set :/
          git sparse-checkout add -p 'scripts'
          ls -la
      